"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___BookCategory = BookCategory
class _BookCategory(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BookCategory.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    MYSTERY = BookCategory.V(0)
    SCIENCE_FICTION = BookCategory.V(1)
    SELF_HELP = BookCategory.V(2)
class BookCategory(metaclass=_BookCategory):
    V = typing.NewType('V', builtins.int)
MYSTERY = BookCategory.V(0)
SCIENCE_FICTION = BookCategory.V(1)
SELF_HELP = BookCategory.V(2)

class RecommendationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    USER_ID_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    MAX_RESULTS_FIELD_NUMBER: builtins.int
    user_id: builtins.int = ...
    category: global___BookCategory.V = ...
    max_results: builtins.int = ...

    def __init__(self,
        *,
        user_id : builtins.int = ...,
        category : global___BookCategory.V = ...,
        max_results : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"category",b"category",u"max_results",b"max_results",u"user_id",b"user_id"]) -> None: ...
global___RecommendationRequest = RecommendationRequest

class BookRecommendation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    id: builtins.int = ...
    title: typing.Text = ...

    def __init__(self,
        *,
        id : builtins.int = ...,
        title : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id",b"id",u"title",b"title"]) -> None: ...
global___BookRecommendation = BookRecommendation

class RecommendationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RECOMMENDATIONS_FIELD_NUMBER: builtins.int

    @property
    def recommendations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BookRecommendation]: ...

    def __init__(self,
        *,
        recommendations : typing.Optional[typing.Iterable[global___BookRecommendation]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"recommendations",b"recommendations"]) -> None: ...
global___RecommendationResponse = RecommendationResponse
